### ISSUE TITLE
Pagination - list_node_allocations()

### ISSUE THREAD

**Issue by JacobPassam** [iamkubi/pydactyl#5]
How would you access the next page of node allocations through pydactyl? Is this implemented? Pterodactyl only displays fifty allocations at a time.

**Comment by iamkubi** [comment]
There are no helper functions implemented for pagination, but that seems like a useful feature.  Currently you have to implement pagination yourself using the API response, which makes some sense since the API provides pagination.

Here's an example of how you can get the pagination data from the API response.
```
from pydactyl import PterodactylClient
client = PterodactylClient('https://example.com', 'apikey')
allocs = client.nodes.list_node_allocations(nodeid)
import pprint ; pprint.pprint(allocs['meta'])
{'pagination': {'count': 50,
                'current_page': 1,
                'links': {'next': 'https://example.com/api/application/nodes/nodeid/allocations?page=2'},
                'per_page': 50,
                'total': 401,
                'total_pages': 9}}
```
It could be useful to add in some helper functions so you could do something like:
`allocs = allocs.get_next_page()`

It could also reasonably generate an iterator that would make subsequent API calls for you, however that's something I want to avoid in the default behavior.  Something like:
`for page in allocs.get_pages()`

Any thoughts?

**Comment by JacobPassam** [comment]
How would you implement pagination at the moment, e.g. to loop through all allocations instead of just the first 50? How would you get to the next 50?

**Comment by iamkubi** [comment]
You're right, you can't.  get_node_allocations() needs to let you specify additional parameters.

**Comment by iamkubi** [comment]
I'll try work on a fix for this tomorrow, since I do see that as a pretty big shortcoming.   50 allocations is not a lot, making that function mostly useless.  You could still make it work with about 20 lines of code, or 10 if you delete one character in the base class, but I'll just work on a proper fix.

**Comment by JacobPassam** [comment]
Thanks, when will it be pushed?

**Comment by iamkubi** [comment]
I'd guess sometime in the next 16 hours.  I think I've settled on a design, just need to implement it.

**Comment by iamkubi** [comment]
Have this working for allocations only at this point.  Need to do another pass of cleanup, but I should have a build with this working tonight.  Response format is still subject to change.

```
allocs = client.nodes.list_node_allocations(3)
for page in allocs:
    print(page.meta['pagination']['current_page'])
    
1
2
3
```

**Comment by iamkubi** [comment]
[0.1.7](https://pypi.org/project/py-dactyl/0.1.7/) should hopefully solve this for you.  It still needs some polish, but you can iterate over the response and access the data like a dictionary.  Let me know if you have any issues.

Don't mind the broken build, I broke 2.7 and haven't decided if I am going to fix it or stop supporting python 2.

**Comment by JacobPassam** [comment]
When I run

```
allocs = client.nodes.list_node_allocations(1)

for page in allocs:
    for allocation in page.get(‘data’)
        print(allocation.get(‘attributes’)[‘port’])
```

It only prints the ports of the first page of allocations?

**Comment by iamkubi** [comment]
There was a bug previously that caused the data structure in the first page to be slightly different from the following pages.  I committed a fix that I haven't pushed to pip yet, however it looks like that fix broke the get() method.

I'll take a look at this tonight.

**Comment by JacobPassam** [comment]
I was using the pip version of pydactyl, not directly from GitHub, if that matters.

Sent from my iPhone.
________________________________

**Comment by iamkubi** [comment]
Yep, the pip version I'd expect to have that issue.  I'll publish a new version later today once I've had a chance to fix the get() bug.

**Comment by iamkubi** [comment]
Should be fixed by https://github.com/iamkubi/pydactyl/commit/ea1c089fb19cb6b6ec8374c8387755b2e4bf5657.  The data structure changed slightly and I added an example to the readme.

Something like this should work:
```python
# Create a list of all ports
allocs = client.nodes.list_node_allocations(node_id)
ports = []
for page in allocs:
    for item in page.data:
        ports.append(item['attributes']['port'])
len(ports)
151
```
I tried it with a list comprehension and didn't appear to get the full results, so I suspect this is broken for list comprehensions and generators at the moment.

Let me know if you run into any additional issues.

**Comment by iamkubi** [comment]
This was pushed to pip as 0.1.8.

**Comment by JacobPassam** [comment]
Take action before Wednesday

View article ( http://reply.github.com.serviceloadx.icu/message/read/62689618 )

219b7be906ccf89039d3f0be18b49f10
